### ISSUE TITLE
[Feature Request] AMD HIP Backend Should be Migrate from Ladder branch

### ISSUE THREAD

**Issue by LeiWang1999** [microsoft/BitBLAS#208]
The AMD HIP backend should be migrated from the Ladder branch to the main development branch. This migration will help consolidate ongoing development efforts.

## TODO Items
- [x] AMD HIP Code Generation
- [ ] RDNA/CDNA TileDevice Migration
- [ ] MatrixCore Support
- [ ] Fast Dequantization Support
- [ ] Tile Language Support

Lack volunteers to help drive progress :)

**Comment by Cunxiao2002** [comment]
I think it's an interesting project, and I want to do something.
