### ISSUE TITLE
[Feature Request] Default Backend Should be changed into `tilelang` instead of `tvm` before v0.0.1 release

### ISSUE THREAD

**Issue by LeiWang1999** [microsoft/BitBLAS#252]
We propose changing the default backend from tvm to tilelang before the v0.0.1 release. The tilelang backend has demonstrated compatibility with all current operators (e.g., Matmul, Flash Attention) and offers significant performance advantages.

## TODO Items
- [x] Implement all tilelang templates for current operators
- [x] Make all operators test pass.
- [x] Evaluate the performance variants.

**Comment by LeiWang1999** [comment]
ref to release plan #150

**Comment by LeiWang1999** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/wanglei/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/wanglei/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


config | tir | tl
-- | -- | --
1-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None | 0.303 | 0.304
1-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 0.087 | 0.087
1-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 0.089 | 0.09
1-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 0.17 | 0.154
1-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 0.051 | 0.051
32-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None | 0.326 | 0.348
32-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 0.159 | 0.611
32-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 0.166 | 0.611
32-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 0.177 | 0.186
32-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 0.113 | 0.146
128-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None0 | 0.423 | 0.453
128-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 0.428 | 0.405
128-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 0.472 | 0.421
128-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 0.313 | 0.233
128-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 0.273 | 0.295
512-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None1 | 1.097 | 1.364
512-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 1.388 | 1.206
512-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 1.544 | 1.278
512-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 0.779 | 0.629
512-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 0.85 | 0.797
16384-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None36 | 37.259 | 36.038
16384-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 33.878 | 33.896
16384-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 37.392 | 37.301
16384-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 23.506 | 17.365
16384-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 24.608 | 21.205



</body>

</html>

**Comment by LeiWang1999** [comment]
TL with Split K Support Performance:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/T-LEIW~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/T-LEIW~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


config | tir | tl | tl+splitk | tl/tir | tl/tir-splitk
-- | -- | -- | -- | -- | --
1-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None | 0.303 | 0.304 | 0.303 | 0.996710526 | 1
1-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 0.087 | 0.087 | 0.087 | 1 | 1
1-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 0.089 | 0.09 | 0.09 | 0.988888889 | 0.988888889
1-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 0.17 | 0.154 | 0.154 | 1.103896104 | 1.103896104
1-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 0.051 | 0.051 | 0.051 | 1 | 1
32-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None | 0.326 | 0.348 | 0.331 | 0.936781609 | 0.98489426
32-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 0.159 | 0.611 | 0.117 | 0.260229133 | 1.358974359
32-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 0.166 | 0.611 | 0.124 | 0.271685761 | 1.338709677
32-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 0.177 | 0.186 | 0.171 | 0.951612903 | 1.035087719
32-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 0.113 | 0.146 | 0.108 | 0.773972603 | 1.046296296
128-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None | 0.423 | 0.453 | 0.434 | 0.933774834 | 0.974654378
128-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 0.428 | 0.405 | 0.323 | 1.056790123 | 1.325077399
128-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 0.472 | 0.421 | 0.349 | 1.121140143 | 1.35243553
128-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 0.313 | 0.233 | 0.221 | 1.343347639 | 1.416289593
128-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 0.273 | 0.295 | 0.199 | 0.925423729 | 1.371859296
512-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None | 1.097 | 1.364 | 1.175 | 0.804252199 | 0.933617021
512-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 1.388 | 1.206 | 1.154 | 1.150912106 | 1.202772964
512-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 1.544 | 1.278 | 1.21 | 1.208137715 | 1.276033058
512-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 0.779 | 0.629 | 0.794 | 1.238473768 | 0.981108312
512-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 0.85 | 0.797 | 0.942 | 1.066499373 | 0.902335456
16384-16384-16384-float16-float16-float16-float16-nt-False--1-False-False-None | 37.259 | 36.038 | 35.585 | 1.033880903 | 1.047042293
16384-16384-16384-float16-int4-float16-float16-nt-False--1-False-False-None | 33.878 | 33.896 | 33.514 | 0.999468964 | 1.010861133
16384-16384-16384-float16-int4-float16-float16-nt-False--1-True-False-None | 37.392 | 37.301 | 37.847 | 1.002439613 | 0.987977911
16384-16384-16384-int8-int8-int8-int32-nt-False--1-False-False-None | 23.506 | 17.365 | 16.707 | 1.353642384 | 1.406955168
16384-16384-16384-int8-int2-int8-int32-nt-False--1-False-False-None | 24.608 | 21.205 | 19.441 | 1.160481019 | 1.265778509



</body>

</html>

Let's make a new pull request to change the default backend into tilelang

**Comment by LeiWang1999** [comment]
Closed as be modified at pr #270
